# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -c "import subprocess, sys; sys.exit(0 if subprocess.call([sys.executable, '-m', 'pytest']) in [0, 5] else 1)"
        language: system
        pass_filenames: false
        always_run: true
      - id: strings-to-avoid
        name: strings-to-avoid
        entry: python check_strings.py
        language: system
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        name: nbstripout - Strip outputs from notebooks (auto-fixes)
        entry: python -m nbstripout --extra-keys metadata.colab metadata.kernelspec cell.metadata.colab cell.metadata.executionInfo cell.metadata.id cell.metadata.outputId
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        entry: python -m pre_commit_hooks.check_added_large_files --maxkb=5120
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
        exclude: '\.Rd'
        entry: python -m pre_commit_hooks.end_of_file_fixer
      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)
        entry: python -m pre_commit_hooks.trailing_whitespace_fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort - Sort python imports (auto-fixes)
        entry: python -m isort --profile black  --line-length 79 --filter-files
  - repo: https://github.com/psf/black
    rev: 23.12.1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: black - consistent Python code formatting (auto-fixes)
        entry: python -m black --line-length=79
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8 - Python linting
        entry: python -m flake8
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-isort
        name: nbqa-isort - Sort Python imports (notebooks; auto-fixes)
        entry: python -m nbqa isort --nbqa-mutate
        additional_dependencies: [ isort==5.13.2 ]
      - id: nbqa-black
        name: nbqa-black - consistent Python code formatting (notebooks; auto-fixes)
        entry: python -m nbqa black
        additional_dependencies: [ black==23.12.1 ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: detect-secrets - Detect secrets in staged code
        entry: python -m detect_secrets.pre_commit_hook --base64-limit=4
