options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.smoke
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}